# docker-compose.yml
version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: cmcp_postgres
    restart: always
    environment:
      POSTGRES_USER: cmcp
      POSTGRES_PASSWORD: cmpc
      POSTGRES_DB: cmpc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cmcp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
